/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register */
    post: operations['register_auth_register_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description OAuth2 form login: `username` is the user's email. Also powers Swagger's Authorize button.
     */
    post: operations['login_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Me */
    get: operations['read_me_users_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Me */
    patch: operations['update_me_users_me_patch']
    trace?: never
  }
  '/users/me/preferences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update My Preferences
     * @description Save the food preferences; the first save completes the sign-up.
     */
    put: operations['update_my_preferences_users_me_preferences_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/meals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search Meals
     * @description Public search: active meals with at least one upcoming slot.
     */
    get: operations['search_meals_meals_get']
    put?: never
    /** Create Meal */
    post: operations['create_meal_meals_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/meals/mine': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List My Meals */
    get: operations['list_my_meals_meals_mine_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/meals/{meal_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Meal
     * @description Public; the host's food preferences are included only for logged-in users.
     */
    get: operations['get_meal_meals__meal_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update Meal
     * @description Also used to hide (`is_active: false`) or re-publish a meal.
     */
    patch: operations['update_meal_meals__meal_id__patch']
    trace?: never
  }
  '/meals/{meal_id}/slots': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add Slots */
    post: operations['add_slots_meals__meal_id__slots_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/meals/{meal_id}/slots/{slot_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Slot */
    delete: operations['delete_slot_meals__meal_id__slots__slot_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Allergen
     * @description The 14 allergens that EU Regulation 1169/2011 requires to be declared.
     * @enum {string}
     */
    Allergen:
      | 'gluten'
      | 'crustaceans'
      | 'eggs'
      | 'fish'
      | 'peanuts'
      | 'soy'
      | 'milk'
      | 'tree_nuts'
      | 'celery'
      | 'mustard'
      | 'sesame'
      | 'sulphites'
      | 'lupin'
      | 'molluscs'
    /** Body_login_auth_login_post */
    Body_login_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null
      /** Username */
      username: string
      /**
       * Password
       * Format: password
       */
      password: string
      /**
       * Scope
       * @default
       */
      scope: string
      /** Client Id */
      client_id?: string | null
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null
    }
    /**
     * BringCategory
     * @description What a guest may bring to a meal.
     * @enum {string}
     */
    BringCategory: 'drinks' | 'dessert' | 'starter' | 'side' | 'bread' | 'fruit'
    /**
     * Diet
     * @enum {string}
     */
    Diet: 'omnivore' | 'vegetarian' | 'vegan' | 'pescatarian' | 'no_pork' | 'halal' | 'kosher'
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string
    }
    /**
     * FavoriteFood
     * @enum {string}
     */
    FavoriteFood:
      | 'italian'
      | 'mediterranean'
      | 'asian'
      | 'japanese'
      | 'indian'
      | 'mexican'
      | 'middle_eastern'
      | 'spicy'
      | 'seafood'
      | 'meat'
      | 'vegetarian_dishes'
      | 'desserts'
      | 'street_food'
      | 'homestyle'
    /**
     * FoodPreferences
     * @description Answered at sign-up (mandatory) and editable from the profile. Replaces all values.
     */
    FoodPreferences: {
      diet: components['schemas']['Diet']
      /**
       * Allergies
       * @description Empty = no allergies
       */
      allergies?: components['schemas']['Allergen'][]
      /** Allergy Notes */
      allergy_notes?: string | null
      /** Favorite Foods */
      favorite_foods?: components['schemas']['FavoriteFood'][]
      /** Disliked Foods */
      disliked_foods?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string
    }
    /**
     * HostPreferences
     * @description The host's food preferences: health data, so only shown to logged-in users.
     */
    HostPreferences: {
      diet: components['schemas']['Diet'] | null
      /** Allergies */
      allergies: components['schemas']['Allergen'][]
      /** Allergy Notes */
      allergy_notes: string | null
      /** Disliked Foods */
      disliked_foods: string | null
    }
    /**
     * HostPublic
     * @description What other users can see about a host: no surname, no email.
     */
    HostPublic: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** First Name */
      first_name: string
      /** City */
      city: string | null
      /** Bio */
      bio: string | null
      /** Avatar Url */
      avatar_url: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** MealCreate */
    MealCreate: {
      /** Title */
      title: string
      /** Description */
      description: string
      meal_type: components['schemas']['MealType']
      /**
       * Estimated Value Cents
       * @description Meals are free: what the host would charge per person, in euro cents
       */
      estimated_value_cents: number
      /** Max Guests */
      max_guests: number
      /** City */
      city: string
      /** Neighborhood */
      neighborhood?: string | null
      /** Guest Can Bring */
      guest_can_bring?: components['schemas']['BringCategory'][]
      /** Bring Notes */
      bring_notes?: string | null
      /** Allergens */
      allergens?: components['schemas']['Allergen'][]
      /** Suitable Diets */
      suitable_diets?: components['schemas']['Diet'][]
      /** Slots */
      slots?: components['schemas']['SlotCreate'][]
    }
    /** MealRead */
    MealRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Description */
      description: string
      meal_type: components['schemas']['MealType']
      /** Estimated Value Cents */
      estimated_value_cents: number
      /** Max Guests */
      max_guests: number
      /** City */
      city: string
      /** Neighborhood */
      neighborhood: string | null
      /** Guest Can Bring */
      guest_can_bring: components['schemas']['BringCategory'][]
      /** Bring Notes */
      bring_notes: string | null
      /** Allergens */
      allergens: components['schemas']['Allergen'][]
      /** Suitable Diets */
      suitable_diets: components['schemas']['Diet'][]
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      host: components['schemas']['HostPublic']
      /** @description Only present when the request is authenticated */
      host_preferences?: components['schemas']['HostPreferences'] | null
      /** Slots */
      slots: components['schemas']['SlotRead'][]
    }
    /**
     * MealType
     * @enum {string}
     */
    MealType: 'breakfast' | 'brunch' | 'lunch' | 'aperitif' | 'dinner'
    /**
     * MealUpdate
     * @description Partial update: only the fields sent by the client are changed.
     */
    MealUpdate: {
      /** Title */
      title?: string
      /** Description */
      description?: string
      meal_type?: components['schemas']['MealType']
      /** Estimated Value Cents */
      estimated_value_cents?: number
      /** Max Guests */
      max_guests?: number
      /** City */
      city?: string
      /** Neighborhood */
      neighborhood?: string | null
      /** Guest Can Bring */
      guest_can_bring?: components['schemas']['BringCategory'][]
      /** Bring Notes */
      bring_notes?: string | null
      /** Allergens */
      allergens?: components['schemas']['Allergen'][]
      /** Suitable Diets */
      suitable_diets?: components['schemas']['Diet'][]
      /** Is Active */
      is_active?: boolean
    }
    /** SlotCreate */
    SlotCreate: {
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string
      /**
       * Capacity
       * @description Defaults to the meal's max_guests
       */
      capacity?: number | null
    }
    /** SlotRead */
    SlotRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string
      /** Capacity */
      capacity: number
    }
    /** Token */
    Token: {
      /** Access Token */
      access_token: string
      /**
       * Token Type
       * @default bearer
       */
      token_type: string
    }
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
      /** First Name */
      first_name: string
      /** Last Name */
      last_name: string
    }
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Email
       * Format: email
       */
      email: string
      /** First Name */
      first_name: string
      /** Last Name */
      last_name: string
      /** Bio */
      bio: string | null
      /** City */
      city: string | null
      /** Avatar Url */
      avatar_url: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      diet: components['schemas']['Diet'] | null
      /** Allergies */
      allergies: components['schemas']['Allergen'][]
      /** Allergy Notes */
      allergy_notes: string | null
      /** Favorite Foods */
      favorite_foods: components['schemas']['FavoriteFood'][]
      /** Disliked Foods */
      disliked_foods: string | null
      /** Has Completed Preferences */
      has_completed_preferences: boolean
    }
    /**
     * UserUpdate
     * @description Partial update: only the fields sent by the client are changed.
     */
    UserUpdate: {
      /** First Name */
      first_name?: string
      /** Last Name */
      last_name?: string
      /** Bio */
      bio?: string | null
      /** City */
      city?: string | null
      /** Avatar Url */
      avatar_url?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  register_auth_register_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_login_auth_login_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Token']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_me_users_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  update_me_users_me_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_my_preferences_users_me_preferences_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodPreferences']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_meals_meals_get: {
    parameters: {
      query?: {
        city?: string | null
        meal_type?: components['schemas']['MealType'] | null
        /** @description Only meals with a slot on this day */
        day?: string | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_meal_meals_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MealCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealRead']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_my_meals_meals_mine_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealRead'][]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_meal_meals__meal_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meal_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealRead']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_meal_meals__meal_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        meal_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MealUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealRead']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_slots_meals__meal_id__slots_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        meal_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SlotCreate'][]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MealRead']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_slot_meals__meal_id__slots__slot_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        slot_id: string
        meal_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
